"use client";

// import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/components/Header";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const viewport: Viewport = {
//   width: "device-width",
//   initialScale: 1,
//   viewportFit: "cover",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoginPage = usePathname().includes("login");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen bg-gradient-to-br from-gray-900 via-slate-900 to-gray-800 pattern-financial-professional relative bg-[#1A1A1B]">
          <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
            {/* Base gradient foundation */}
            <div className="absolute inset-0">
              <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-slate-900 via-gray-900 to-slate-800"></div>
              <div className="absolute top-0 right-0 w-3/4 h-3/4 bg-gradient-radial from-blue-900/15 via-blue-800/8 to-transparent"></div>
              <div className="absolute bottom-0 left-0 w-2/3 h-2/3 bg-gradient-radial from-emerald-900/12 via-emerald-800/6 to-transparent"></div>
              <div className="absolute top-1/2 left-1/2 w-1/2 h-1/2 bg-gradient-radial from-purple-900/10 via-purple-800/5 to-transparent transform -translate-x-1/2 -translate-y-1/2"></div>
            </div>

            {/* Enhanced liquid patterns */}
            <svg
              className="absolute inset-0 w-full h-full opacity-[0.10]"
              viewBox="0 0 1200 800"
              preserveAspectRatio="none"
            >
              <defs>
                <linearGradient
                  id="liquidGradient1"
                  x1="0%"
                  y1="0%"
                  x2="100%"
                  y2="100%"
                >
                  <stop
                    offset="0%"
                    style={{
                      stopColor: "rgba(59, 130, 246, 0.625)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="50%"
                    style={{
                      stopColor: "rgba(16, 185, 129, 0.5)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="100%"
                    style={{
                      stopColor: "rgba(168, 85, 247, 0.375)",
                      stopOpacity: 1,
                    }}
                  />
                </linearGradient>
                <linearGradient
                  id="liquidGradient2"
                  x1="100%"
                  y1="0%"
                  x2="0%"
                  y2="100%"
                >
                  <stop
                    offset="0%"
                    style={{
                      stopColor: "rgba(16, 185, 129, 0.5)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="50%"
                    style={{
                      stopColor: "rgba(59, 130, 246, 0.375)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="100%"
                    style={{
                      stopColor: "rgba(6, 182, 212, 0.5)",
                      stopOpacity: 1,
                    }}
                  />
                </linearGradient>
                <linearGradient
                  id="liquidGradient3"
                  x1="50%"
                  y1="0%"
                  x2="50%"
                  y2="100%"
                >
                  <stop
                    offset="0%"
                    style={{
                      stopColor: "rgba(168, 85, 247, 0.5)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="100%"
                    style={{
                      stopColor: "rgba(59, 130, 246, 0.375)",
                      stopOpacity: 1,
                    }}
                  />
                </linearGradient>
                <linearGradient
                  id="liquidGradient4"
                  x1="25%"
                  y1="0%"
                  x2="75%"
                  y2="100%"
                >
                  <stop
                    offset="0%"
                    style={{
                      stopColor: "rgba(6, 182, 212, 0.375)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="50%"
                    style={{
                      stopColor: "rgba(168, 85, 247, 0.25)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="100%"
                    style={{
                      stopColor: "rgba(16, 185, 129, 0.375)",
                      stopOpacity: 1,
                    }}
                  />
                </linearGradient>
                <linearGradient
                  id="liquidGradient5"
                  x1="75%"
                  y1="25%"
                  x2="25%"
                  y2="75%"
                >
                  <stop
                    offset="0%"
                    style={{
                      stopColor: "rgba(99, 102, 241, 0.375)",
                      stopOpacity: 1,
                    }}
                  />
                  <stop
                    offset="100%"
                    style={{
                      stopColor: "rgba(236, 72, 153, 0.25)",
                      stopOpacity: 1,
                    }}
                  />
                </linearGradient>
              </defs>

              {/* Enhanced liquid wave shapes */}
              <path
                d="M 0,450 Q 150,320 300,420 Q 450,520 600,380 Q 750,240 900,400 Q 1050,560 1200,420 L 1200,800 L 0,800 Z"
                fill="url(#liquidGradient1)"
                opacity="0.75"
              />
              <path
                d="M 0,250 Q 200,150 400,240 Q 600,330 800,200 Q 1000,70 1200,220 L 1200,0 L 0,0 Z"
                fill="url(#liquidGradient2)"
                opacity="0.625"
              />
              <path
                d="M 0,650 Q 300,570 600,630 Q 900,690 1200,610 L 1200,800 L 0,800 Z"
                fill="url(#liquidGradient3)"
                opacity="0.5"
              />
              <path
                d="M 0,500 Q 100,440 200,490 Q 400,550 600,460 Q 800,370 1000,450 Q 1100,500 1200,440 L 1200,800 L 0,800 Z"
                fill="url(#liquidGradient4)"
                opacity="0.44"
              />
              <path
                d="M 0,320 Q 250,260 500,310 Q 750,360 1200,280 L 1200,0 L 0,0 Z"
                fill="url(#liquidGradient5)"
                opacity="0.375"
              />
            </svg>

            {/* Enhanced organic blob shapes */}
            <div className="absolute top-20 right-24 w-80 h-80 opacity-[0.075]">
              <div
                className="w-full h-full bg-gradient-radial from-blue-500/50 via-blue-400/25 to-transparent rounded-full transform rotate-12 animate-pulse shadow-2xl blur-sm"
                style={{
                  borderRadius: "60% 40% 30% 70% / 60% 30% 70% 40%",
                  filter: "drop-shadow(0 0 35px rgba(59, 130, 246, 0.25))",
                }}
              ></div>
              <div
                className="absolute inset-4 w-3/4 h-3/4 bg-gradient-radial from-cyan-400/30 to-transparent rounded-full transform -rotate-25 animate-pulse"
                style={{
                  borderRadius: "40% 60% 50% 50% / 30% 70% 40% 60%",
                  animationDelay: "1s",
                }}
              ></div>
            </div>

            <div className="absolute bottom-32 left-16 w-64 h-64 opacity-[0.0625]">
              <div
                className="w-full h-full bg-gradient-radial from-emerald-500/55 via-emerald-400/30 to-transparent rounded-full transform -rotate-45 animate-pulse shadow-2xl blur-sm"
                style={{
                  borderRadius: "40% 60% 70% 30% / 40% 70% 30% 60%",
                  animationDelay: "2s",
                  filter: "drop-shadow(0 0 30px rgba(16, 185, 129, 0.25))",
                }}
              ></div>
              <div
                className="absolute inset-6 w-2/3 h-2/3 bg-gradient-radial from-blue-400/25 to-transparent rounded-full transform rotate-30 animate-pulse"
                style={{
                  borderRadius: "70% 30% 40% 60% / 30% 70% 60% 40%",
                  animationDelay: "3s",
                }}
              ></div>
            </div>

            <div className="absolute top-1/3 left-1/4 w-48 h-48 opacity-[0.05]">
              <div
                className="w-full h-full bg-gradient-radial from-purple-500/60 via-purple-400/35 to-transparent rounded-full transform rotate-45 animate-pulse shadow-2xl blur-sm"
                style={{
                  borderRadius: "30% 70% 40% 60% / 70% 40% 60% 30%",
                  animationDelay: "4s",
                  filter: "drop-shadow(0 0 25px rgba(168, 85, 247, 0.3))",
                }}
              ></div>
            </div>

            {/* Additional floating blobs */}
            <div className="absolute top-2/3 right-1/3 w-40 h-40 opacity-[0.044]">
              <div
                className="w-full h-full bg-gradient-radial from-pink-500/37 via-pink-400/18 to-transparent rounded-full transform -rotate-60 animate-pulse"
                style={{
                  borderRadius: "50% 50% 80% 20% / 60% 40% 60% 40%",
                  animationDelay: "5s",
                }}
              ></div>
            </div>

            <div className="absolute top-1/4 right-1/5 w-36 h-36 opacity-[0.0375]">
              <div
                className="w-full h-full bg-gradient-radial from-cyan-500/44 via-cyan-400/25 to-transparent rounded-full transform rotate-75 animate-pulse"
                style={{
                  borderRadius: "80% 20% 40% 60% / 20% 80% 70% 30%",
                  animationDelay: "6s",
                }}
              ></div>
            </div>

            {/* Enhanced noise texture overlay */}
            <div className="absolute inset-0 opacity-[0.05]">
              <div
                className="w-full h-full"
                style={{
                  backgroundImage: `
              radial-gradient(circle at 25% 25%, rgba(255, 255, 255, 0.125) 1px, transparent 1.5px),
              radial-gradient(circle at 75% 75%, rgba(59, 130, 246, 0.19) 0.8px, transparent 1px),
              radial-gradient(circle at 50% 10%, rgba(16, 185, 129, 0.15) 1.2px, transparent 1.5px),
              radial-gradient(circle at 10% 90%, rgba(168, 85, 247, 0.125) 0.6px, transparent 1px),
              radial-gradient(circle at 80% 20%, rgba(6, 182, 212, 0.1) 0.5px, transparent 0.8px),
              radial-gradient(circle at 20% 80%, rgba(236, 72, 153, 0.087) 0.8px, transparent 1px),
              radial-gradient(circle at 60% 60%, rgba(251, 191, 36, 0.075) 0.6px, transparent 0.8px)
            `,
                  backgroundSize:
                    "120px 120px, 160px 160px, 200px 200px, 180px 180px, 240px 240px, 220px 220px, 150px 150px",
                }}
              ></div>
            </div>

            {/* Enhanced starfield effect */}
            <div className="absolute inset-0 opacity-[0.0375]">
              <div
                className="w-full h-full"
                style={{
                  backgroundImage: `
              radial-gradient(circle at 15% 35%, rgba(255, 255, 255, 0.25) 0.3px, transparent 0.3px),
              radial-gradient(circle at 85% 65%, rgba(59, 130, 246, 0.31) 0.2px, transparent 0.2px),
              radial-gradient(circle at 45% 85%, rgba(16, 185, 129, 0.25) 0.25px, transparent 0.25px),
              radial-gradient(circle at 75% 15%, rgba(168, 85, 247, 0.19) 0.15px, transparent 0.15px)
            `,
                  backgroundSize:
                    "350px 350px, 450px 450px, 400px 400px, 500px 500px",
                  animation: "twinkle 8s ease-in-out infinite",
                }}
              ></div>
            </div>

            {/* Enhanced flowing particle streams */}
            <div className="absolute inset-0 opacity-[0.075]">
              <div
                className="absolute top-16 left-0 w-full h-1.5 bg-gradient-to-r from-transparent via-blue-400/50 to-transparent transform rotate-12 animate-pulse shadow-lg"
                style={{
                  filter: "drop-shadow(0 0 12px rgba(59, 130, 246, 0.375))",
                }}
              ></div>
              <div
                className="absolute top-40 left-0 w-full h-1 bg-gradient-to-r from-transparent via-emerald-400/44 to-transparent transform -rotate-6 animate-pulse shadow-lg"
                style={{
                  animationDelay: "1s",
                  filter: "drop-shadow(0 0 10px rgba(16, 185, 129, 0.31))",
                }}
              ></div>
              <div
                className="absolute top-80 left-0 w-full h-2 bg-gradient-to-r from-transparent via-purple-400/37 to-transparent transform rotate-3 animate-pulse shadow-lg"
                style={{
                  animationDelay: "3s",
                  filter: "drop-shadow(0 0 15px rgba(168, 85, 247, 0.44))",
                }}
              ></div>
              <div
                className="absolute bottom-32 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-cyan-400/37 to-transparent transform rotate-8 animate-pulse shadow-lg"
                style={{
                  animationDelay: "5s",
                  filter: "drop-shadow(0 0 11px rgba(6, 182, 212, 0.375))",
                }}
              ></div>

              {/* Additional diagonal streams */}
              <div
                className="absolute top-1/4 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-pink-400/31 to-transparent transform rotate-45 animate-pulse"
                style={{ animationDelay: "2s" }}
              ></div>
              <div
                className="absolute top-3/4 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-yellow-400/25 to-transparent transform -rotate-12 animate-pulse"
                style={{ animationDelay: "4s" }}
              ></div>
              <div
                className="absolute top-1/2 left-0 w-full h-1 bg-gradient-to-r from-transparent via-indigo-400/31 to-transparent transform rotate-20 animate-pulse"
                style={{ animationDelay: "6s" }}
              ></div>
            </div>

            {/* Enhanced animated liquid bubbles */}
            <div
              className="absolute top-32 right-40 w-4 h-4 bg-blue-400/44 rounded-full animate-pulse shadow-lg"
              style={{
                filter: "drop-shadow(0 0 10px rgba(59, 130, 246, 0.5))",
              }}
            ></div>
            <div
              className="absolute top-64 left-32 w-3 h-3 bg-emerald-400/37 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "1s",
                filter: "drop-shadow(0 0 7px rgba(16, 185, 129, 0.44))",
              }}
            ></div>
            <div
              className="absolute bottom-48 right-28 w-5 h-5 bg-purple-400/37 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "2s",
                filter: "drop-shadow(0 0 12px rgba(168, 85, 247, 0.56))",
              }}
            ></div>
            <div
              className="absolute bottom-24 left-48 w-2 h-2 bg-cyan-400/44 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "0.5s",
                filter: "drop-shadow(0 0 6px rgba(6, 182, 212, 0.5))",
              }}
            ></div>
            <div
              className="absolute top-2/3 right-1/5 w-3.5 h-3.5 bg-blue-400/37 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "1.5s",
                filter: "drop-shadow(0 0 11px rgba(59, 130, 246, 0.44))",
              }}
            ></div>
            <div
              className="absolute top-1/4 left-3/4 w-2.5 h-2.5 bg-emerald-400/31 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "2.5s",
                filter: "drop-shadow(0 0 8px rgba(16, 185, 129, 0.5))",
              }}
            ></div>

            {/* Additional enhanced bubbles */}
            <div
              className="absolute top-1/8 left-1/3 w-2 h-2 bg-pink-400/37 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "3s",
                filter: "drop-shadow(0 0 5px rgba(236, 72, 153, 0.56))",
              }}
            ></div>
            <div
              className="absolute bottom-1/3 right-1/4 w-3 h-3 bg-yellow-400/31 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "3.5s",
                filter: "drop-shadow(0 0 7px rgba(251, 191, 36, 0.5))",
              }}
            ></div>
            <div
              className="absolute top-3/4 left-1/8 w-2.5 h-2.5 bg-indigo-400/37 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "4s",
                filter: "drop-shadow(0 0 6px rgba(99, 102, 241, 0.5))",
              }}
            ></div>
            <div
              className="absolute top-1/2 right-1/8 w-1.5 h-1.5 bg-orange-400/44 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "4.5s",
                filter: "drop-shadow(0 0 4px rgba(251, 146, 60, 0.56))",
              }}
            ></div>
            <div
              className="absolute bottom-1/8 left-2/3 w-3 h-3 bg-violet-400/31 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "5s",
                filter: "drop-shadow(0 0 10px rgba(139, 92, 246, 0.44))",
              }}
            ></div>
            <div
              className="absolute top-5/6 right-2/3 w-2 h-2 bg-rose-400/37 rounded-full animate-pulse shadow-lg"
              style={{
                animationDelay: "5.5s",
                filter: "drop-shadow(0 0 7px rgba(251, 113, 133, 0.5))",
              }}
            ></div>

            {/* Enhanced glowing energy lines */}
            <svg
              className="absolute inset-0 w-full h-full opacity-[0.087]"
              viewBox="0 0 1200 800"
              preserveAspectRatio="none"
            >
              <defs>
                <filter id="glow">
                  <feGaussianBlur stdDeviation="4" result="coloredBlur" />
                  <feMerge>
                    <feMergeNode in="coloredBlur" />
                    <feMergeNode in="SourceGraphic" />
                  </feMerge>
                </filter>
              </defs>

              {/* Primary energy flows */}
              <path
                d="M 0,320 Q 200,270 400,340 Q 600,410 800,300 Q 1000,190 1200,260"
                stroke="rgba(59, 130, 246, 0.625)"
                strokeWidth="2"
                fill="none"
                strokeLinecap="round"
                filter="url(#glow)"
                opacity="1"
              />
              <path
                d="M 0,520 Q 300,440 600,500 Q 900,560 1200,480"
                stroke="rgba(16, 185, 129, 0.5)"
                strokeWidth="1.5"
                fill="none"
                strokeLinecap="round"
                filter="url(#glow)"
                opacity="0.875"
              />
              <path
                d="M 0,120 Q 400,70 800,140 Q 1000,170 1200,100"
                stroke="rgba(168, 85, 247, 0.44)"
                strokeWidth="1.2"
                fill="none"
                strokeLinecap="round"
                filter="url(#glow)"
                opacity="0.75"
              />

              {/* Secondary flowing lines */}
              <path
                d="M 0,200 Q 250,150 500,210 Q 750,270 1200,180"
                stroke="rgba(6, 182, 212, 0.375)"
                strokeWidth="1"
                fill="none"
                strokeLinecap="round"
                filter="url(#glow)"
                opacity="0.625"
              />
              <path
                d="M 0,650 Q 350,600 700,650 Q 950,700 1200,620"
                stroke="rgba(236, 72, 153, 0.31)"
                strokeWidth="1"
                fill="none"
                strokeLinecap="round"
                filter="url(#glow)"
                opacity="0.5"
              />
              <path
                d="M 0,80 Q 300,30 600,90 Q 900,150 1200,60"
                stroke="rgba(251, 191, 36, 0.25)"
                strokeWidth="0.8"
                fill="none"
                strokeLinecap="round"
                filter="url(#glow)"
                opacity="0.375"
              />

              {/* Intersecting diagonal flows */}
              <path
                d="M 0,400 Q 400,350 800,420 Q 1000,450 1200,380"
                stroke="rgba(139, 92, 246, 0.31)"
                strokeWidth="1"
                fill="none"
                strokeLinecap="round"
                filter="url(#glow)"
                opacity="0.5"
              />
            </svg>

            {/* Enhanced ambient light spots */}
            <div className="absolute top-4 left-4 w-16 h-16 bg-gradient-radial from-blue-500/25 via-blue-400/12 to-transparent rounded-full blur-lg animate-pulse"></div>
            <div
              className="absolute top-4 right-4 w-20 h-20 bg-gradient-radial from-emerald-500/19 via-emerald-400/10 to-transparent rounded-full blur-lg animate-pulse"
              style={{ animationDelay: "1s" }}
            ></div>
            <div
              className="absolute bottom-4 left-4 w-18 h-18 bg-gradient-radial from-purple-500/22 via-purple-400/11 to-transparent rounded-full blur-lg animate-pulse"
              style={{ animationDelay: "2s" }}
            ></div>
            <div
              className="absolute bottom-4 right-4 w-14 h-14 bg-gradient-radial from-cyan-500/27 via-cyan-400/14 to-transparent rounded-full blur-lg animate-pulse"
              style={{ animationDelay: "3s" }}
            ></div>

            {/* Additional corner illumination */}
            <div
              className="absolute top-1/4 left-0 w-24 h-24 bg-gradient-radial from-pink-500/15 via-pink-400/7 to-transparent rounded-full blur-xl animate-pulse"
              style={{ animationDelay: "1.5s" }}
            ></div>
            <div
              className="absolute bottom-1/4 right-0 w-28 h-28 bg-gradient-radial from-yellow-500/12 via-yellow-400/6 to-transparent rounded-full blur-xl animate-pulse"
              style={{ animationDelay: "2.5s" }}
            ></div>
            <div
              className="absolute top-0 right-1/3 w-22 h-22 bg-gradient-radial from-indigo-500/19 via-indigo-400/9 to-transparent rounded-full blur-xl animate-pulse"
              style={{ animationDelay: "3.5s" }}
            ></div>
            <div
              className="absolute bottom-0 left-1/3 w-20 h-20 bg-gradient-radial from-violet-500/17 via-violet-400/9 to-transparent rounded-full blur-xl animate-pulse"
              style={{ animationDelay: "4.5s" }}
            ></div>
          </div>

          {/* Header */}
          {!isLoginPage && <Header />}
          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
